### ISSUE TITLE
[Feature Request] - Server version Number

### ISSUE THREAD

**Issue by Nolar-Hack** [riffy/paldmin#12]
Hello,

Thanks for your work on the interface !

Could you add the version number of the server we are runing ? 
Maybe below the active player ?

Regards

**Comment by riffy** [comment]
On the way :) . I expect a 1.1 release today or tomorrow (with some more fine control)

![version](https://github.com/riffy/paldmin/assets/13089522/ec99a2dc-0669-45ae-ad4e-41851e274eaf)

**Comment by Nolar-Hack** [comment]
Perfect :)
thanks you !

**Comment by riffy** [comment]
Added and released in v1.1.1
